# RTL source list, relative to the repo root. Package must come first.
rtl/core/core_pkg.sv
rtl/core/agu.sv
rtl/core/alu.sv
rtl/core/cache_controller.sv
rtl/core/core.sv
rtl/core/data_cache.sv
rtl/core/dependency_mapping_table.sv
rtl/core/dispatch.sv
rtl/core/execute_agu.sv
rtl/core/execute_alu.sv
rtl/core/fifo.sv
rtl/core/free_list.sv
rtl/core/fwrd_unit.sv
rtl/core/instruction_queue.sv
rtl/core/load_data_queue.sv
rtl/core/load_store_unit.sv
rtl/core/miss_status_history_register.sv
rtl/core/RAT.sv
rtl/core/register_file.sv
rtl/core/register_read.sv
rtl/core/rename.sv
rtl/core/reorder_buffer.sv
rtl/core/rotating_priority_arbiter.sv
rtl/core/scheduler.sv
rtl/core/select.sv
rtl/core/store_data_queue.sv
rtl/core/wakeup.sv
